services:
  - type: web
    name: hazina-asilii
    runtime: docker
    repo: https://github.com/masalagosimon442-dotcom/research-hazina-asili
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: HAZINA ASILI
      - key: APP_VERSION
        value: "4.0.0"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://hazina-asilii.onrender.com/
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        value: dpg-d8op1srbc2fs73etrdtg-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: hazina_asili_db_user
      - key: DB_PASS
        value: 58bSrmt6kIuCCEC84VPCpYwG9gbcyliy
      - key: DB_NAME
        value: hazina_asili_db
      - key: DB_SSL
        value: "true"
      - key: SESSION_LIFETIME
        value: "3600"
      - key: RECORDS_PER_PAGE
        value: "15"
      - key: LOGIN_MAX_ATTEMPTS
        value: "5"
      - key: LOGIN_LOCKOUT_MINUTES
        value: "15"
      - key: FORCE_HTTPS
        value: "true"
      - key: ADMIN_PASSWORD
        value: Admin@1234
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: UPLOAD_DIR
        value: assets/uploads/
